#!/usr/bin/env python
# -*- coding: UTF-8 -*-




##################################################
## DEPENDENCIES
import sys
import os
import os.path
try:
    import builtins as builtin
except ImportError:
    import __builtin__ as builtin
from os.path import getmtime, exists
import time
import types
from Cheetah.Version import MinCompatibleVersion as RequiredCheetahVersion
from Cheetah.Version import MinCompatibleVersionTuple as RequiredCheetahVersionTuple
from Cheetah.Template import Template
from Cheetah.DummyTransaction import *
from Cheetah.NameMapper import NotFound, valueForName, valueFromSearchList, valueFromFrameOrSearchList
from Cheetah.CacheRegion import CacheRegion
import Cheetah.Filters as Filters
import Cheetah.ErrorCatchers as ErrorCatchers
from Cheetah.compat import unicode

##################################################
## MODULE CONSTANTS
VFFSL=valueFromFrameOrSearchList
VFSL=valueFromSearchList
VFN=valueForName
currentTime=time.time
__CHEETAH_version__ = '3.2.6.post1'
__CHEETAH_versionTuple__ = (3, 2, 6, 'post', 1)
__CHEETAH_genTime__ = 1774609811.5974321
__CHEETAH_genTimestamp__ = 'Fri Mar 27 12:10:11 2026'
__CHEETAH_src__ = 'WsgiSqlObject_15Watt/Paginator/templates/tplPaginator.tmpl'
__CHEETAH_srcLastModified__ = 'Sun Feb 25 20:16:45 2024'
__CHEETAH_docstring__ = 'Autogenerated by Cheetah: The Python-Powered Template Engine'

if __CHEETAH_versionTuple__ < RequiredCheetahVersionTuple:
    raise AssertionError(
      'This template was compiled with Cheetah version'
      ' %s. Templates compiled before version %s must be recompiled.'%(
         __CHEETAH_version__, RequiredCheetahVersion))

##################################################
## CLASSES

class tplPaginator(Template):

    ##################################################
    ## CHEETAH GENERATED METHODS


    def __init__(self, *args, **KWs):

        super(tplPaginator, self).__init__(*args, **KWs)
        if not self._CHEETAH__instanceInitialized:
            cheetahKWArgs = {}
            allowedKWs = 'searchList namespaces filter filtersLib errorCatcher'.split()
            for k,v in KWs.items():
                if k in allowedKWs: cheetahKWArgs[k] = v
            self._initCheetahInstance(**cheetahKWArgs)
        

    def respond(self, trans=None):



        ## CHEETAH: main method generated for this template
        if (not trans and not self._CHEETAH__isBuffering and not callable(self.transaction)):
            trans = self.transaction # is None unless self.awake() was called
        if not trans:
            trans = DummyTransaction()
            _dummyTrans = True
        else: _dummyTrans = False
        write = trans.response().write
        SL = self._CHEETAH__searchList
        _filter = self._CHEETAH__currentFilter
        
        ########################################
        ## START - generated method body
        
        if VFFSL(SL,"paginator.pageCount",True) > 1: # generated from line 2, col 1
            write('''    <div class="dbPaginatorOuter">
        <ul>
            <li class="first"><a href="?page=1">«</a></li>

            <li class="prev">
''')
            if VFFSL(SL,"paginator.prevPage",True) is not None: # generated from line 8, col 17
                write('''                <a href="?page=''')
                _v = VFFSL(SL,"paginator.prevPage",True) # '$paginator.prevPage' on line 9, col 32
                if _v is not None: write(_filter(_v, rawExpr='$paginator.prevPage')) # from line 9, col 32.
                write('''">&lt</a>
''')
            else: # generated from line 10, col 17
                write('''                &nbsp;
''')
            write('''            </li>
            <li class="next">
''')
            if VFFSL(SL,"paginator.nextPage",True) is not None: # generated from line 15, col 17
                write('''                <a href="?page=''')
                _v = VFFSL(SL,"paginator.nextPage",True) # '$paginator.nextPage' on line 16, col 32
                if _v is not None: write(_filter(_v, rawExpr='$paginator.nextPage')) # from line 16, col 32.
                write('''">&gt</a>
''')
            else: # generated from line 17, col 17
                write('''                &nbsp;
''')
            write('''            </li>
            <li class="last"><a href="?page=''')
            _v = VFFSL(SL,"paginator.lastPage",True) # '$paginator.lastPage' on line 21, col 45
            if _v is not None: write(_filter(_v, rawExpr='$paginator.lastPage')) # from line 21, col 45.
            write('''">»</a></li>
        </ul>
        <br>
        Seite ''')
            _v = VFFSL(SL,"paginator.currentPage",True) # '$paginator.currentPage' on line 24, col 15
            if _v is not None: write(_filter(_v, rawExpr='$paginator.currentPage')) # from line 24, col 15.
            write(''' von ''')
            _v = VFFSL(SL,"paginator.pageCount",True) # '$paginator.pageCount' on line 24, col 42
            if _v is not None: write(_filter(_v, rawExpr='$paginator.pageCount')) # from line 24, col 42.
            write('''
    </div>
''')
        
        ########################################
        ## END - generated method body
        
        return _dummyTrans and trans.response().getvalue() or ""
        
    ##################################################
    ## CHEETAH GENERATED ATTRIBUTES


    _CHEETAH__instanceInitialized = False

    _CHEETAH_version = __CHEETAH_version__

    _CHEETAH_versionTuple = __CHEETAH_versionTuple__

    _CHEETAH_genTime = __CHEETAH_genTime__

    _CHEETAH_genTimestamp = __CHEETAH_genTimestamp__

    _CHEETAH_src = __CHEETAH_src__

    _CHEETAH_srcLastModified = __CHEETAH_srcLastModified__

    _mainCheetahMethod_for_tplPaginator = 'respond'

## END CLASS DEFINITION

if not hasattr(tplPaginator, '_initCheetahAttributes'):
    templateAPIClass = getattr(tplPaginator,
                               '_CHEETAH_templateClass',
                               Template)
    templateAPIClass._addCheetahPlumbingCodeToClass(tplPaginator)


# CHEETAH was developed by Tavis Rudd and Mike Orr
# with code, advice and input from many other volunteers.
# For more information visit https://cheetahtemplate.org/

##################################################
## if run from command line:
if __name__ == '__main__':
    from Cheetah.TemplateCmdLineIface import CmdLineIface
    CmdLineIface(templateObj=tplPaginator()).run()


